# Site settings
title: Mapping [murals somewhere]
header-img: img.home-bg.jpg
email: your@yours
copyright_name: mappingsomething
description: "This project maps murals somewhere"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: something
github_username:  something

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
